config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'components', to: "pages#components"

  get 'about', to: "pages#about"

  get 'contact', to: "pages#contact"

  devise_for :users

  resources :gardens, only: [:index, :show] do
    resources :allotments, only: [:new, :create]
  end

  resources :users, only: [:index, :show]

  namespace :user do
    resource :profile, only: [:show, :edit, :update]
    resources :allotments, only: [:index] do
      member do
        patch :cancel
      end
    resources :garden_reviews, only: [:new, :create]
    end
  end


  namespace :owner do
    resource :garden
    resource :profile, only: [:show, :edit, :update]

    resources :allotments, only: [:index, :show] do
      member do
        patch :accept
        patch :decline
      end

      resources :user_reviews, only: [:new, :create]
    end
  end
end

app/views/shared/_edit_profile.html.erb
<!-- When you call this partial you should pass these two variable: path, user  -->
<div class="edit-profile">
  <div class="log-in-wrapper">
    <div class="container">
      <div class="edit-profile-form-box">
        <div class="edit-profile-form-title">
          <h2>Pas je profiel aan</h2>
        </div>

        <%= simple_form_for(user, url: path) do |f| %>
        <div class="form-inputs">
          <%= f.input :first_name, label: "voornaam" %>
          <%= f.input :last_name, label: "achternaam" %>
          <%= f.input :description, label: "beschrijving", as: :text, :input_html => {:maxlength => 500}, placeholder: 'Vertel iets over jezelf en waar je naar opzoek bent bij Jouw Stek..' %>
        </div>
        <div class="edit-profile-btn">
        <div class="user-picture">
         <%= image_tag(user.photo, class: "avatar-small") %>
        </div>
          <%= f.input :photo, label: 'profielfoto' %>
          <%= f.input :photo_cache, as: :hidden %>
          <div class="form-actions">
            <%= f.button :submit, "Updaten", class: "btn-success" %>
          </div>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer-links">
  <div class="space-between-links"><%= link_to "over ons", about_path, class: "footer-links-hoover" %></div>
    <div class="space-between-links"><%= link_to "contact", contact_path, class: "footer-links-hoover"  %></div>
  </div>
  <div class="section-title-border-footer">
  </div>
  <div class="footer-social">
    <%= link_to "", "https://www.facebook.com/Jouw-Stek-301552580290262/", class: "fa fa-facebook footer-icons btn-footer" %>
  </div>
</div>

app/views/shared/_garden_form.html.erb
<div class="garden-new">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6 form-group">
        <div class="garden-form-box">
          <div class="garden-form-title"><h2>Hi <%=current_user.first_name %>, <small> welkom bij de Jouw Stek gemeenschap</small></h2></div>

          <%= simple_form_for(@garden, url: owner_garden_path) do |g| %>
          <%= g.error_notification %>

          <%= g.input :title, :input_html => {:maxlength => 80}, placeholder: 'Omschrijf je tuin in 5 woorden' %>
          <%= g.input :address, :input_html => {:maxlength => 50}, placeholder: 'Straat + huisnummer' %>
          <%= g.input :city, :input_html => {:maxlength => 50}, placeholder: 'Stad' %>
          <%= g.input :description, as: :text, :input_html => {:maxlength => 1000}, placeholder: 'Vertel in maximaal honderd woorden wat er uniek is aan jouw tuin en wat jouw verwachtingen zijn. Bijvoorbeeld het oppervlakte, de soorten planten die er groeien.' %>

          <div class="btn-form-garden">
            <%= g.input :photo, label: 'afbeelding 1' %>
            <%= g.input :photo2, label: 'afbeelding 2'  %>
            <%= g.input :photo3, label: 'afbeelding 3'  %>
          </div>

          <%= g.button :submit, "verzenden", class: "btn btn-success" %>
          <% end %>
        </div>
       </div>
     </div>
  </div>
</div>

app/views/shared/_hexagons.html.erb
<div class="container hidden-xs" id="hex-container">
  <div class="cirle-arrow">
    <a href="#hex-container"><i class="fa fa-angle-down" style="color: black;"></i></a>
  </div>
  <div class="hexes">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs" id="hex1">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb6.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col-xs-12 col-sm-6">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs" id="hex2">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb1.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class=" col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs hidden-sm hidden-md" id="hex3">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'hex-photo2.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex" id="hex4">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb3.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs hidden-sm hidden-md" id="hex5">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'hex-photo1.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs" id="hex6">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb4.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col-xs-12 col-sm-6">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs" id="hex7">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb5.jpg' %>);">
                <%= link_to gardens_path %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class=" col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs hidden-sm hidden-md" id="hex8">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'moestuin1.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs" id="hex9">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'hex-photo3.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4">
        <%= link_to gardens_path do %>
        <div class="hex hidden-xs hidden-sm hidden-md" id="hex10">
          <div class="hexagon hexagon1">
            <div class="hexagon-in1">
              <div class="hexagon-in2" style= "background: url(<%= image_path 'afb2.jpg' %>);">
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map" style="width: 100%; height: 100vh;">
   <% content_for(:after_js) do %>
   <script>
   $(document).on('ready', function() {
   handler = Gmaps.build('Google');
   handler.buildMap({ internal: { id: 'map' },  provider: {styles: [ {
        "featureType": "administrative",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#ff0300"
            },
            {
                "saturation": -100
            },
            {
                "lightness": 129.33333333333334
            },
            {
                "gamma": 1
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#abff00"
            },
            {
                "saturation": 61.80000000000001
            },
            {
                "lightness": 13.800000000000011
            },
            {
                "gamma": 1
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#366328"
            },
            {
                "weight": "0.10"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway.controlled_access",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road.highway.controlled_access",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#00b7ff"
            },
            {
                "saturation": -31.19999999999996
            },
            {
                "lightness": 2.1803921568627374
            },
            {
                "gamma": 1
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#00B5FF"
            },
            {
                "saturation": -33.33333333333343
            },
            {
                "lightness": 27.294117647058826
            },
            {
                "gamma": 1
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "transit.line",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "transit.station.bus",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "hue": "#00B7FF"
            },
            {
                "saturation": 8.400000000000006
            },
            {
                "lightness": 36.400000000000006
            },
            {
                "gamma": 1
            }
        ]
    }], scrollwheel: false } }, function(){
   markers = handler.addMarkers(<%= raw @markers.to_json %>);
   handler.bounds.extendWith(markers);
   // handler.fitMapToBounds();
   handler.getMap().setZoom(13);
   handler.map.centerOn([52.368830, 4.896332]);
 });
})
</script>
<% end %>
</div>

app/views/shared/_navbar.html.erb
  <!-- Logo -->
  <% if params[:controller] == "pages" && params[:action] == "home" %>  
  <div class="navbar-wagon flex-end">
    <% else %>
    <div class="navbar-wagon space-between">
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo_white.png" %>
      <% end %>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right">
<!-- LOGGED IN: logo, about, search, my profile, my bookings, my gardens, log out, message
  NOT LOGGED IN: logo, about, search, login, join -->

  <!--  <%= link_to t(".about", default: "About"), about_path, class: "navbar-wagon-item navbar-wagon-link" %> -->

  <!-- Different navigation if login or not -->
  <% if user_signed_in? %>

  <!-- Notification -->


  <div class="navbar-wagon-item">
    <div class="dropdown">
      <% if current_user.first_name.nil? %>
      <%= link_to "Jouw profiel", user_profile_path, class:"user-name" %>
      <% else %>
      <%= link_to user_profile_path, class:"user-name" do %>
      <%= current_user.first_name %>
      <span class="green-underline"></span>
      <% end %>
      <% end %>
      <%= cl_image_tag current_user.photo, cl_image_options_avatar_thumb(class:"avatar-small dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown")%>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".profile", default: "Profiel"), user_profile_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% if current_user.garden %>
        <li><%= link_to t(".allotments", default: "Boekingen"), owner_allotments_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
        <li><%= link_to t(".allotments", default: "Boekingen"), user_allotments_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
        <% if current_user.garden %>
        <li><%= link_to t(".garden", default: "Mijn Stek"), owner_garden_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
        <li><%= link_to t(".destroy", default: "Uitloggen"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>

  <% if !current_user.garden %>
  <% if params[:controller] == "pages" && params[:action] == "home" %>  
  <%= link_to "voeg jouw stek toe", new_owner_garden_path, {class: "navbar-wagon-item btn-success-inverted"} %>
  <% else %>
  <%= link_to "voeg jouw stek toe", new_owner_garden_path, {class: "navbar-wagon-item btn-success"} %>
  <% end %>

  <% end %>

  <% else %>

  <!-- Login text link -->
  <%= link_to "Log in", new_user_session_path, {class: "navbar-wagon-item btn-success"} %>

  <!-- Button (call-to-action) -->
  <%= link_to "Account aanmaken", "#", {class: "navbar-wagon-item btn-success", "data-toggle": "modal", "data-target": "#sign-up"} %>

  <% end %>

  <!-- Search form -->
<!-- <form action="" class="navbar-wagon-search">
  <input type="text" class="navbar-wagon-search-input" placeholder="Search">
    <button type="submit" class="navbar-wagon-search-btn">
      <i class="fa fa-search"></i>
    </button>
  </form> -->

</div>

</div>

app/views/shared/_reviews.html.erb
<div class="reviews-form" >
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6 form-group">
        <div class="review-form-box">
          <h2>Hoi <%= @current_user.first_name %>, <small>schrijf een review </small></h2>
          <%= simple_form_for(review, url: path) do |g| %>
          <%= g.error_notification %>

          <%= g.input :description, label: "beschrijving", as: :text, :input_html => {:maxlength => 500}, placeholder: 'Vertel ons over jouw ervaring..' %>
          <%= g.input :stars, label: "sterren",  as: :select, :collection => [1, 2, 3, 4, 5] %>

          <div class="btn-review">
          <%= g.button :submit, "verstuur review", class: "btn-success" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_geocode.html.erb
<%= form_tag classifieds_path, method: :get do %>
  <%= label :location, "Search classifieds near : " %>
  <%= text_field_tag :location, params[:location] %>

  <%= label :distance, "Distance : " %>
  <%= text_field_tag :distance, params[:distance] %>

  <%= submit_tag "Search" %>
<% end %>

app/views/shared/_show_garden.html.erb
<div class="">
  <% garden.photos.each do |photo| %>
  <%= link_to photo.url, class: "swipebox", id: "swipebox-first" do %>
  <%= cl_image_tag photo, cl_image_options_banner_extra_large(class: "garden-image") %>
  <% end %>
  <% end %>
</div>

<div class="wrapper-white-about">
  <div class="container">
    <div id="container-garden-top">
      <%= link_to gardens_path do %>
      <div class="search-results ">
        <div class="fa fa-chevron-left icon"></div>
        <div class="link">Naar alle tuinen</div>
      </div>
      <% end  %>
    </div>



    <div id="container-garden-details">
      <div>
        <div>
          <h2> <%= garden.title %></h2>
        </div>
        <div>
         <p> 
           <%= garden.address %> 
         </p> 
         <p>
         Geplaatst op <%= garden.created_at.strftime("%d-%m-%Y") %> 
         </p>
       </div>
     </div>
     <div class="avatar-user-container">
       <div class="avatar-user">
         <%= link_to cl_image_tag(garden.owner.photo, cl_image_options_avatar_thumb( class: "avatar-small")), user_path(garden.owner), { class: "avatar-link card-user" } %>
       </div>
       <div class="garden-owner-fullname">
        <%= @garden.owner.fullname %>
      </div>
    </div>
  </div>

  <div id="container-garden-details">
    <div class="garden-description">
     <p> <%= garden.description %></p>
   </div>
   <div class="button-garden-view">
    <% if user_signed_in? && current_user.garden %>
    <% else %>
    <div class="button-garden"><%= link_to "Tuinier in deze tuin", new_garden_allotment_path(@garden), {class: "btn btn-success" } %></div>
    <% end %>
    <% if user_signed_in? %>
    <% if current_user.garden == garden %>
    <div class="buttons-garden"><%= link_to "", edit_owner_garden_path, class:"fa fa-pencil" %>
    </div>
    <div class="buttons-garden"><%= link_to "", owner_garden_path, method: :delete, data: {confirm: "Weet je zeker dat je tuin wil verwijderen?"}, class:"fa fa-trash-o" %></div>
    <% end %>
    <% end %>
  </div>
</div>

<div id="container-garden-pictures">
  <div class="swipebox2">
    <% garden.photos.each do |photo| %>
    <%= link_to photo.url, class: "swipebox" do %>
    <%= cl_image_tag photo, cl_image_options_banner_large(class: "garden-photo-swipebox") %>
    <% end %>
    <% end %>
  </div>
</div>

<% if current_user != @garden.owner %>
<div id="container-garden-owner">
  <div class="garden-description">
    <h4>Leer onze Stek-Eigenaar <%= garden.owner.first_name %> kennen:</h4>
    <br>
    <p><%= @garden.owner.description %></p>
  </div>
</div>
<% end %>

<% if @garden.garden_reviews.exists? %>
<div id="container-garden-details">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="text-center"><h3>Reviews</h3>
          <div class="section-title-border"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <% garden.garden_reviews.each do |review| %>
      <div class="col-xs-12 col-sm-6" >
        <div class="review-cards" >
          <div class="circle">
            <%= cl_image_tag review.user.photo, cl_image_options_avatar_medium(class: "avatar-medium", id: "avatar-review") %>
          </div>
          <div class="review-name">
            <p> <%= review.user.fullname %></p>
          </div>
          <div class="review-text">
            <p><%= review.description %></p>
          </div>
          <div class="carrots">
            <% review.stars.times do %>
            <%= image_tag "carrot_full.png", class: "small-icon"%>
            <% end %>
            <% (5 - review.stars).times do %>
            <%= image_tag "carrot_empty.png",  class: "small-icon"%>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

<div id="container-map-details">
  <div id="garden-map" lat="<%= @garden.latitude %>" lon="<%= @garden.longitude %>" style="max-width: 900px; height: 400px;"></div>

  <% content_for(:after_js) do %>
  <script type="text/javascript">
    var myLatlng = new google.maps.LatLng($('#garden-map').attr('lat'), $('#garden-map').attr('lon'));

    var myOptions = {
      zoom: 16,
      center: myLatlng,
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      styles: [{
        "featureType": "administrative",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
        {
          "hue": "#ff0300"
        },
        {
          "saturation": -100
        },
        {
          "lightness": 129.33333333333334
        },
        {
          "gamma": 1
        },
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
        {
          "hue": "#abff00"
        },
        {
          "saturation": 61.80000000000001
        },
        {
          "lightness": 13.800000000000011
        },
        {
          "gamma": 1
        },
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "off"
        }
        ]
      },
      {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "on"
        },
        {
          "color": "#1fa661"
        },
        {
          "weight": "0.55"
        }
        ]
      },
      {
        "featureType": "road.highway",
        "elementType": "labels.icon",
        "stylers": [
        {
          "visibility": "off"
        }
        ]
      },
      {
        "featureType": "road.highway.controlled_access",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "road.highway.controlled_access",
        "elementType": "labels.icon",
        "stylers": [
        {
          "visibility": "off"
        }
        ]
      },
      {
        "featureType": "road.arterial",
        "elementType": "all",
        "stylers": [
        {
          "hue": "#00b7ff"
        },
        {
          "saturation": -31.19999999999996
        },
        {
          "lightness": 2.1803921568627374
        },
        {
          "gamma": 1
        },
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "road.local",
        "elementType": "all",
        "stylers": [
        {
          "hue": "#00B5FF"
        },
        {
          "saturation": -33.33333333333343
        },
        {
          "lightness": 27.294117647058826
        },
        {
          "gamma": 1
        },
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "transit.line",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "off"
        }
        ]
      },
      {
        "featureType": "transit.station.airport",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "on"
        }
        ]
      },
      {
        "featureType": "transit.station.bus",
        "elementType": "all",
        "stylers": [
        {
          "visibility": "off"
        }
        ]
      },
      {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
        {
          "hue": "#00B7FF"
        },
        {
          "saturation": 8.400000000000006
        },
        {
          "lightness": 36.400000000000006
        },
        {
          "gamma": 1
        }
        ]
              }] // TODO: replace [] by array from https://snazzymaps.com/
            };

            var map = new google.maps.Map(document.getElementById('garden-map'), myOptions);
            var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: "You are here!"
            });
          </script>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_show_user.html.erb
<div class="wrapper-white-about">
  <div class="container">
    <div class="user-container">
      <div class="user-container-text">
        <div class="row">
          <div class="col-xs-12" style="padding: 20px">
            <%= cl_image_tag  @user.photo, cl_image_options_avatar_large(class: "avatar-extralarge")%>
            <h3><%= @user.fullname %></h3>
            <div class="user-description"><%= @user.description %></div>
            <div><% if current_user == @user %><%= link_to "pas je profiel aan", edit_user_profile_path, { class: "btn btn-success"} %></div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
    <% if @user.user_reviews.exists? %>
        <div class="user-container2">
          <div class="row">
            <div class="col-xs-12"><h3>Reviews</h3>
              <div class="section-title-border"></div>
            </div>
          </div>

          <div class="row">
            <% @user.user_reviews.each do |review| %>
              <div class="col-xs-12 col-sm-6">
                <div class="review-cards-user">
                  <%= link_to user_profile_path(@user) do %>
                    <div class="circle">
                      <%= cl_image_tag review.owner.photo,  cl_image_options_avatar_large(class: "avatar-medium", id: "avatar-review") %>
                    </div>
                  <% end %>
                  <div class="review-name">
                    <p> <%= review.owner.fullname %></p>
                  </div>
                  <div class="review-text">
                    <p><%= review.description %></p>
                  </div>
                  <div class="carrots">
                    <% review.stars.times do %>
                      <%= image_tag "carrot_full.png", class: "small-icon"%>
                    <% end %>
                    <% (5 - review.stars).times do %>
                      <%= image_tag "carrot_empty.png",  class: "small-icon"%>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>