config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'components', to: "pages#components"

  get 'about', to: "pages#about"

  get 'contact', to: "pages#contact"

  devise_for :users

  resources :gardens, only: [:index, :show] do
    resources :allotments, only: [:new, :create]
  end

  resources :users, only: [:index, :show]

  namespace :user do
    resource :profile, only: [:show, :edit, :update]
    resources :allotments, only: [:index] do
      member do
        patch :cancel
      end
    resources :garden_reviews, only: [:new, :create]
    end
  end


  namespace :owner do
    resource :garden
    resource :profile, only: [:show, :edit, :update]

    resources :allotments, only: [:index, :show] do
      member do
        patch :accept
        patch :decline
      end

      resources :user_reviews, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_one :garden, dependent: :destroy, foreign_key: 'owner_id'

  has_many :allotments, dependent: :destroy
  has_many :garden_allotments, through: :garden, source: "allotments"
  has_many :garden_reviews, dependent: :destroy
  has_many :user_reviews, dependent: :destroy
  has_many :owner_reviews, dependent: :destroy, class_name: 'UserReview', foreign_key: 'owner_id'

  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  def fullname
    "#{first_name} #{last_name}"
  end

  def garden_destroyable?
    self.garden.allotments.each do |allotment|
      if allotment.request_status == "pending"
        return false
      end
    end
    return true
  end

  def profile_complete?
    if self.first_name.nil? || self.last_name.nil? || self.photo.nil? || self.description.nil?
      return false
    end
      return true
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_profile_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :photo, :photo_cache)
  end
end

app/controllers/user/allotments_controller.rb
class User::AllotmentsController < ApplicationController

   before_action :find_allotment, only: [ :cancel ]

  def index
    @allotments = current_user.allotments
  end

  def cancel
    @allotment.request_status = "cancelled"
     if @allotment.save
      redirect_to user_allotments_path
    else
      flash[:warning] = 'Het was niet mogelijk om de boeking te annuleren'
      redirect_to user_allotments_path
    end
  end

private

  def find_allotment
    @allotment = Allotment.find(params[:id])
  end

end

app/controllers/user/garden_reviews_controller.rb
class User::GardenReviewsController < ApplicationController

   before_action :find_allotment

  def new
    @garden_review = GardenReview.new
  end

  def create
    @garden_review = GardenReview.new(garden_review_params)
    @garden_review.user = current_user
    @garden_review.allotment = @allotment
    if @garden_review.save!
      @garden = @allotment.garden_id
      redirect_to garden_path(@garden)
    else
      flash[:warning] = 'Het was niet mogelijk een tuin-review aan te maken'
      redirect_to garden_path(@garden)
    end
  end

private

  def find_allotment
    @allotment = current_user.allotments.find(params[:allotment_id])
  end

  def garden_review_params
    params.require(:garden_review).permit(:description, :stars)
  end

  def find_garden
    @garden = @allotment.garden_id
  end

end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_profile_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :photo, :photo_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :description, :photo, :photo_cache)
  end
end

app/views/user/profile/edit.html.erb
<h2>Edit your profile</h2>
<%= simple_form_for(@user, url: profile_path) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/user/profile/show.html.erb
<div class="user-container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @user.fullname %></h1>
      <%= cl_image_tag  @user.photo, class: "avatar-extralarge" %>
      <p><%= @user.description %></p> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae quaerat omnis fuga eos similique quos odio ratione neque. Soluta ducimus saepe omnis repellat natus similique dicta aspernatur blanditiis, eum placeat quisquam eius officiis ullam sint. Vero sapiente voluptates, saepe placeat necessitatibus consequuntur tenetur quisquam illum magnam. Fugiat rerum doloremque earum? </p>
    </div>
  </div>
</div>

<% if @user.owner_reviews.exists? %>
<div class="review-container">
  <div class="row">
    <div class="col-xs-12">
      <div style="text-align: center"><h3>Reviews</h3></div>
      <div class="section-title-border">
      </div>
    </div>
  </div>
  <% @user.owner_reviews.each do |review| %>
  <div class="review-cards">
    <div class="row">
      <div class="col-xs-2" style="padding-left: 50px">
        <%= cl_image_tag  @user.photo, class: "avatar-large" %>
      </div>
      <div class="col-xs-10">
        <% review.stars.times do %>
        <i class="fa fa-star"></i>
        <% end %>
        <% (5 - review.stars).times do %>
        <i class="fa fa-star-o"></i>
        <% end %>
        <p><%= review.description %></p>
        <div class="review-name">
         <p><%= review.user.fullname %></p>
         <%#raise%>
       </div>
     </div>
   </div>
 </div>
 <% end %>
</div>
<% end %>

<%= link_to "Edit", edit_profile_path, { class: "btn-success"} %>

<% if @user.garden %>
<div class="review-container">
  <div class="row">
    <div class="col-xs-12">
      <div style="text-align: center"><h3>Garden</h3></div>
      <div class="section-title-border">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6">
      <div class="garden-image">

        <%= cl_image_tag @user.garden.photo, height: 300, width: 400, crop: :fill %>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="text-garden">
        <p> Address: <%= @user.garden.address %></p>
        <p> Description: <%= @user.garden.description %></p>
      </div>
    </div>
  </div>
</div>
<% end %>