config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  get 'components', to: "pages#components"

  get 'about', to: "pages#about"

  get 'contact', to: "pages#contact"

  devise_for :users

  resources :gardens, only: [:index, :show] do
    resources :allotments, only: [:new, :create]
  end

  resources :users, only: [:index, :show]

  namespace :user do
    resource :profile, only: [:show, :edit, :update]
    resources :allotments, only: [:index] do
      member do
        patch :cancel
      end
    resources :garden_reviews, only: [:new, :create]
    end
  end


  namespace :owner do
    resource :garden
    resource :profile, only: [:show, :edit, :update]

    resources :allotments, only: [:index, :show] do
      member do
        patch :accept
        patch :decline
      end

      resources :user_reviews, only: [:new, :create]
    end
  end
end

app/views/shared/booking/_booking_form.html.erb
<div class="garden-new">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6 form-group">
        <div class="garden-form-box">
          <div class="garden-form-title"><h2>Hi <%=current_user.first_name %>, <small> welcome to the community</small></h2></div>

          <%= simple_form_for(@garden, url: owner_garden_path) do |g| %>
          <%= g.error_notification %>

          <%= g.input :title, :input_html => {:maxlength => 80}, placeholder: 'Sunny garden facing south' %>
          <%= g.input :address, :input_html => {:maxlength => 50}, placeholder: 'Prinsengracht 250' %>
          <%= g.input :city, :input_html => {:maxlength => 50}, placeholder: 'Amsterdam' %>
          <%= g.input :description, as: :text, :input_html => {:maxlength => 1000}, placeholder: 'Describe in max 100 words typical charasteristics of your garden. For example size in square meter, type of ground, type plants, expectations etc.' %>

          <div class="btn-form-garden">
            <%= g.input :photo, label: 'picture 1' %>
            <%= g.input :photo2, label: 'picture 2'  %>
            <%= g.input :photo3, label: 'picture 3'  %>
          </div>

          <%= g.button :submit, "share garden", class: "btn btn-success" %>
          <% end %>
        </div>
       </div>
     </div>
  </div>
</div>

app/views/shared/booking/_content_owner.html.erb
<div class="booking-item">
  <div class="booking-item-user">
   <div><%= link_to cl_image_tag(allotment.user.photo, cl_image_options_avatar_large(class: "avatar-large")), user_path(allotment.user) %></div>
    <div class="booking-item-user-name"><%= allotment.user.fullname %></div>
  </div>
  <div class="booking-item-data">
    <%= allotment.start_day.strftime("%A, %b %d")%>
    <br>
    <%= allotment.end_day.strftime("%A, %b %d")%>
  </div>
  <div class="booking-item-message"><%= allotment.message %></div>
  <div class="booking-item-side">
    <div><% if allotment.request_status == "pending" %>
      <%= link_to "accepteer", accept_owner_allotment_path(allotment), class: "btn btn-success btn-sm booking-item-btn", method: :patch %>
      <%= link_to "afwijzen", decline_owner_allotment_path(allotment), class: "btn btn-danger btn-sm booking-item-btn", method: :patch %>
      <% elsif allotment.request_status == "accepted" %>
      <%= link_to "schrijf review", new_owner_allotment_user_review_path(allotment), class: "btn btn-success btn-sm" %>
    <% end %>
  </div>
 </div>
</div>

app/views/shared/booking/_content_user.html.erb
<div class="booking-item">
  <div class="booking-item-owner">
    <div class="booking-picture">
    <%= link_to cl_image_tag(allotment.garden.owner.photo, cl_image_options_avatar_large(class: "avatar-small")), user_path(allotment.garden.owner)%>
    </div>
    <div><%= allotment.garden.owner.fullname %></div>
  </div>
  <div class="booking-item-thumb"><%= link_to cl_image_tag(allotment.garden.photo, cl_image_options_avatar_large(class: "avatar-large")), garden_path(allotment.garden)%></div>
<div class="booking-item-infos">
  <div class="booking-item-street"><%= allotment.garden.address %></div>
  <div class="booking-item-city"><%= allotment.garden.city %></div>
</div>
<div class="booking-item-message"><%= allotment.message %></div>
<div class="booking-item-data">
  <%= allotment.start_day.strftime("%A, %b %d")%>
  <br>
  <%= allotment.end_day.strftime("%A, %b %d")%>
</div>
  <div class="booking-item-side">
    <div class="booking-item-btn"><% if allotment.request_status == "pending" %>
      <%= link_to "cancel", cancel_user_allotment_path(allotment), class: "btn btn-success btn-sm", method: :patch %>
      <% elsif allotment.request_status == "accepted" %>
      <%= link_to "write review", new_user_allotment_garden_review_path(allotment), class: "btn btn-success btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/booking/_index.html.erb
<div class="container">
  <div class="booking-welcome-text">
    <h2>Hi <%= @current_user.first_name %>, <small> dit zijn jouw boekingen</small></h2>
  </div>
  <div class="tabs text-align:center">
    <% if params["accepted"] %>
    <a class="tab" data-target="#pending">
      <% else %>
      <a class="tab active" data-target="#pending">
        <% end %>
        <div class="tab-elements">
          <div class="circle-tab">
            <i class="fa fa-question fa-2x"></i></div>
            <div class="tab-text hidden-xs"><p>in afwachting</p></div>
          </div>
        </a>
        <% if params["accepted"] %>
        <a class="tab active" data-target="#accepted">
          <% else %>
          <a class="tab" data-target="#accepted">
            <% end %>
            <div class="tab-elements">
              <div class="circle-tab">
                <i class="fa fa-check fa-2x"></i></div>
                <div class="tab-text hidden-xs"><p>geaccepteerd</p></div>
              </div>
            </a>
            <a class="tab" data-target="#canceled">
              <div class="tab-elements">
               <div class="circle-tab">
                <i class="fa fa-times fa-2x"></i></div>
                <div class="tab-text hidden-xs"><p>afgewezen</p> </div>
              </div>
            </a>
          </div>
          <% if params["accepted"] %>
          <div class="tab-content hidden" id="pending">
            <% else %>
            <div class="tab-content" id="pending">
              <% end %>
              <% if @allotments.empty? %>
              <div class="no-requests">
                <h2><small>Op het moment heb je geen boekingen. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
              </div>
              <% else %>
              <% @allotments.each do |allotment| %>
              <% if allotment.request_status == "pending" %>
              <% if current_user.garden %>
              <%= render "shared/booking/content_owner", allotment: allotment %>
              <% else %>
              <%= render "shared/booking/content_user", allotment: allotment %>
              <% end %>
              <% elsif allotment.request_status.empty? %>
              <div class="no-requests">
                <h2><small>Op het moment heb je geen boekingen in afwachting. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
              </div>
              <% end %>
              <% end %>
              <% end %>
            </div>
            <% if params["accepted"] %>
            <div class="tab-content" id="accepted">
              <% else %>
              <div class="tab-content hidden" id="accepted">
                <% end %>
                <% if @allotments.empty? %>
                <div class="no-requests">
                  <h2><small>Op het moment heb je geen geaccepteerde boekingen. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
                </div>
                <% else %>
                <% @allotments.each do |allotment| %>
                <% if allotment.request_status == "accepted" %>
                <% if current_user.garden %>
                <%= render "shared/booking/content_owner", allotment: allotment %>
                <% else %>
                <%= render "shared/booking/content_user", allotment: allotment %>
                <% end %>
                <% elsif allotment.request_status.empty? %>
                <div class="no-requests">
                  <h2><small>Op het moment heb je geen geaccepteerde boekingen. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
                </div>
                <% end %>
                <% end %>
                <% end %>
              </div>
              <div class="tab-content hidden" id="canceled">
                <% if @allotments.empty? %>
                <div class="no-requests">
                  <h2><small>Op het moment heb je geen afgewezen boekingen. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
                </div>
                <% else %>
                <% @allotments.each do |allotment| %>
                <% if allotment.request_status == "cancelled" || allotment.request_status == "declined"%>
                <% if current_user.garden %>
                <%= render "shared/booking/content_owner", allotment: allotment %>
                <% else %>
                <%= render "shared/booking/content_user", allotment: allotment %>
                <% end %>
                <% elsif allotment.request_status.empty? %>
                <div class="no-requests">
                  <h2><small>Op het moment heb je geen afgewezen boekingen. <br> Je kan <%= link_to 'hier', gardens_path, {class: "link" } %> tuinen bij jou in de buurt bekijken</small></h2>
                </div>
                <% end %>
                <% end %>
                <% end %>
              </div>
            </div>